# Generated by Django 5.1.1 on 2025-08-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('folder', 'Folder'), ('shortcut', 'Shortcut')], default='folder', max_length=20)),
                ('pos_x', models.IntegerField(default=100)),
                ('pos_y', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=255)),
                ('result', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=16)),
                ('wallpaper', models.CharField(default='default', max_length=64)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('volume', models.PositiveIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
